const data = [
    {
        title: "The man who refused to freeze to death",
        author: "William Park",
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed faucibus turpis in eu. Proin fermentum leo vel orci porta non. Euismod nisi porta lorem mollis aliquam. Aliquam vestibulum morbi blandit cursus. Aliquam sem fringilla ut morbi tincidunt augue interdum. Cum sociis natoque penatibus et magnis dis parturient montes. Adipiscing enim eu turpis egestas pretium aenean. Suspendisse sed nisi lacus sed viverra tellus in. Morbi blandit cursus risus at ultrices mi tempus imperdiet. Praesent tristique magna sit amet purus gravida quis blandit turpis. Imperdiet nulla malesuada pellentesque elit eget. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Integer enim neque volutpat ac tincidunt vitae semper. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Sed pulvinar proin gravida hendrerit. Arcu odio ut sem nulla pharetra.

        Nunc sed augue lacus viverra vitae congue. Neque aliquam vestibulum morbi blandit cursus risus at ultrices. Dui faucibus in ornare quam viverra orci. Dignissim suspendisse in est ante in nibh mauris cursus mattis. Risus nullam eget felis eget nunc lobortis mattis aliquam faucibus. Vitae justo eget magna fermentum. Condimentum mattis pellentesque id nibh tortor id aliquet lectus. Lacus sed viverra tellus in hac habitasse. Fringilla ut morbi tincidunt augue. Quis commodo odio aenean sed adipiscing diam. Quis eleifend quam adipiscing vitae proin sagittis nisl. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales.
        
        Nunc sed id semper risus. Mus mauris vitae ultricies leo integer malesuada. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper. Adipiscing commodo elit at imperdiet. Euismod elementum nisi quis eleifend quam. Blandit libero volutpat sed cras ornare arcu dui. Sagittis orci a scelerisque purus semper eget duis at tellus. Nunc sed id semper risus in. Pellentesque habitant morbi tristique senectus et. Imperdiet massa tincidunt nunc pulvinar. Facilisis sed odio morbi quis commodo odio aenean sed. Velit egestas dui id ornare arcu odio ut sem nulla. Aliquam sem fringilla ut morbi.
        
        Etiam tempor orci eu lobortis elementum nibh tellus molestie nunc. Nulla pellentesque dignissim enim sit amet venenatis urna cursus eget. Id venenatis a condimentum vitae sapien pellentesque habitant morbi. Nec ullamcorper sit amet risus nullam eget felis. Turpis egestas integer eget aliquet. Id cursus metus aliquam eleifend mi in nulla. Volutpat odio facilisis mauris sit amet. Aliquam ultrices sagittis orci a scelerisque purus semper eget duis. Nunc non blandit massa enim nec dui nunc mattis enim. Tortor condimentum lacinia quis vel eros donec ac. Aliquam ut porttitor leo a diam sollicitudin tempor. Et molestie ac feugiat sed lectus vestibulum mattis.
        
        Gravida in fermentum et sollicitudin ac orci. Odio tempor orci dapibus ultrices in iaculis. Aliquam etiam erat velit scelerisque in dictum. Luctus accumsan tortor posuere ac ut consequat semper. Commodo viverra maecenas accumsan lacus. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Laoreet non curabitur gravida arcu ac tortor. Quisque id diam vel quam elementum pulvinar etiam. Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Non diam phasellus vestibulum lorem sed risus ultricies. Ornare lectus sit amet est placerat in egestas erat imperdiet. Convallis a cras semper auctor. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Leo urna molestie at elementum eu facilisis.
        
        Ultrices eros in cursus turpis massa tincidunt. Gravida arcu ac tortor dignissim convallis aenean. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec. Porttitor massa id neque aliquam. In metus vulputate eu scelerisque felis imperdiet. Quam viverra orci sagittis eu. Massa placerat duis ultricies lacus sed. Turpis egestas sed tempus urna et pharetra pharetra massa massa. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Nisi quis eleifend quam adipiscing. Aliquam vestibulum morbi blandit cursus risus at ultrices.
        
        Donec enim diam vulputate ut pharetra. Nunc lobortis mattis aliquam faucibus. Eu mi bibendum neque egestas. In fermentum posuere urna nec tincidunt. Turpis egestas integer eget aliquet nibh praesent. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. Molestie at elementum eu facilisis sed. Sapien pellentesque habitant morbi tristique senectus. Metus aliquam eleifend mi in nulla. Quis commodo odio aenean sed adipiscing diam donec adipiscing tristique. Risus quis varius quam quisque id diam vel. At augue eget arcu dictum.
        
        Accumsan in nisl nisi scelerisque eu. Elementum curabitur vitae nunc sed velit dignissim sodales ut eu. Commodo elit at imperdiet dui. Eu lobortis elementum nibh tellus molestie nunc. Morbi tristique senectus et netus et malesuada fames ac turpis. Eget duis at tellus at urna condimentum mattis. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus. Id diam maecenas ultricies mi eget mauris. Eleifend mi in nulla posuere sollicitudin.
        
        In pellentesque massa placerat duis ultricies. Quam quisque id diam vel quam. Congue eu consequat ac felis donec. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Non pulvinar neque laoreet suspendisse interdum consectetur. Tincidunt id aliquet risus feugiat in ante metus dictum. Integer vitae justo eget magna fermentum iaculis. Aliquam ut porttitor leo a diam. Consequat semper viverra nam libero justo laoreet sit amet cursus. Amet consectetur adipiscing elit pellentesque habitant morbi tristique. Tristique sollicitudin nibh sit amet commodo nulla. Euismod nisi porta lorem mollis aliquam ut porttitor leo a. Vitae ultricies leo integer malesuada nunc vel risus commodo viverra.
        
        Commodo elit at imperdiet dui accumsan. Egestas dui id ornare arcu odio. Nunc sed velit dignissim sodales ut. Gravida in fermentum et sollicitudin ac orci. Quisque id diam vel quam elementum pulvinar etiam non. Posuere sollicitudin aliquam ultrices sagittis orci. Vitae suscipit tellus mauris a diam maecenas sed. Vulputate ut pharetra sit amet aliquam. Urna porttitor rhoncus dolor purus non enim praesent elementum facilisis. Purus in mollis nunc sed id semper risus. Amet consectetur adipiscing elit duis. In eu mi bibendum neque egestas congue quisque egestas diam. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Elementum pulvinar etiam non quam lacus suspendisse. Diam volutpat commodo sed egestas egestas fringilla. Rhoncus dolor purus non enim praesent elementum. Vel eros donec ac odio tempor orci dapibus ultrices in.
        
        Ipsum consequat nisl vel pretium lectus quam id. Odio tempor orci dapibus ultrices in iaculis. Consequat semper viverra nam libero justo laoreet sit. Eget arcu dictum varius duis at consectetur. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Diam maecenas sed enim ut sem viverra aliquet. Cras adipiscing enim eu turpis egestas. Volutpat est velit egestas dui id ornare arcu. Leo integer malesuada nunc vel. Pellentesque habitant morbi tristique senectus et netus et. Non consectetur a erat nam at lectus. Volutpat diam ut venenatis tellus in metus.
        
        Risus quis varius quam quisque id diam vel quam. Lobortis scelerisque fermentum dui faucibus in ornare. Lobortis feugiat vivamus at augue eget. Id venenatis a condimentum vitae sapien. Viverra nam libero justo laoreet sit amet cursus. A diam maecenas sed enim ut. Congue eu consequat ac felis donec et. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Leo integer malesuada nunc vel risus commodo. Magna etiam tempor orci eu lobortis elementum nibh. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Tristique et egestas quis ipsum suspendisse. Risus in hendrerit gravida rutrum quisque non. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Molestie a iaculis at erat pellentesque. Ipsum a arcu cursus vitae. Consectetur lorem donec massa sapien faucibus et molestie ac. Viverra maecenas accumsan lacus vel.`
    }
];

export default data
